"""
Mechanical CAD & 3D Printing Engineering Module.
Generates OpenSCAD/FreeCAD 3D parametric models, calculates enclosure clearances,
recommends 3D printing slicer parameters (PLA/ABS/PETG/TPU), and estimates mechanical stress/torque.
"""

from typing import Dict, Any, List, Optional

def generate_openscad_enclosure(
    length_mm: float,
    width_mm: float,
    height_mm: float,
    wall_thickness_mm: float = 2.0,
    screw_hole_diameter_mm: float = 3.2
) -> str:
    """
    Generates a 3D parametric OpenSCAD script for an electronic enclosure lid & base.
    """
    scad_code = f"""// Parametric Electronic Enclosure (Auto-Generated by Agent System)
length = {length_mm};
width = {width_mm};
height = {height_mm};
wall = {wall_thickness_mm};
hole_r = {screw_hole_diameter_mm / 2.0};

module base_box() {{
    difference() {{
        // Outer Box
        cube([length + 2*wall, width + 2*wall, height + wall]);
        
        // Inner Cavity
        translate([wall, wall, wall])
            cube([length, width, height + 1]);
            
        // Corner Mounting Standoff Holes
        translate([wall + 4, wall + 4, -1]) cylinder(h = wall + 2, r = hole_r, $fn=30);
        translate([length + wall - 4, wall + 4, -1]) cylinder(h = wall + 2, r = hole_r, $fn=30);
        translate([wall + 4, width + wall - 4, -1]) cylinder(h = wall + 2, r = hole_r, $fn=30);
        translate([length + wall - 4, width + wall - 4, -1]) cylinder(h = wall + 2, r = hole_r, $fn=30);
    }}
}}

base_box();
"""
    return scad_code

def recommend_slicer_settings(material: str = "PLA", part_type: str = "enclosure") -> Dict[str, Any]:
    """
    Recommends FDM 3D Printing slicer settings based on filament material and part type.
    """
    mat_upper = material.upper()

    settings = {
        "PLA": {
            "nozzle_temp_c": 210,
            "bed_temp_c": 60,
            "print_speed_mms": 60,
            "fan_speed_percent": 100,
            "enclosure_required": False
        },
        "PETG": {
            "nozzle_temp_c": 240,
            "bed_temp_c": 80,
            "print_speed_mms": 50,
            "fan_speed_percent": 50,
            "enclosure_required": False
        },
        "ABS": {
            "nozzle_temp_c": 250,
            "bed_temp_c": 100,
            "print_speed_mms": 45,
            "fan_speed_percent": 0,
            "enclosure_required": True
        },
        "TPU": {
            "nozzle_temp_c": 225,
            "bed_temp_c": 50,
            "print_speed_mms": 25,
            "fan_speed_percent": 80,
            "enclosure_required": False
        }
    }

    mat_config = settings.get(mat_upper, settings["PLA"])

    infill_density = 20
    wall_loops = 3

    if "structural" in part_type.lower() or "gear" in part_type.lower():
        infill_density = 50
        wall_loops = 5

    return {
        "status": "success",
        "material": mat_upper,
        "part_type": part_type,
        "slicer_recommendations": {
            "layer_height_mm": 0.2,
            "infill_density_percent": infill_density,
            "wall_loops": wall_loops,
            "nozzle_temperature_c": mat_config["nozzle_temp_c"],
            "bed_temperature_c": mat_config["bed_temp_c"],
            "print_speed_mms": mat_config["print_speed_mms"],
            "chamber_enclosure_needed": mat_config["enclosure_required"]
        }
    }

def calculate_bolt_torque(bolt_diameter_mm: float, grade: str = "8.8") -> Dict[str, Any]:
    """Calculates tightening torque (Nm) for M-series ISO metric bolts."""
    # Approximate torque formula: T = K * D * F
    d_m = bolt_diameter_mm / 1000.0
    proof_stress_mpa = 640.0 if grade == "8.8" else 830.0  # Grade 10.9
    stress_area_mm2 = 0.7854 * ((bolt_diameter_mm - 0.9382 * 1.0) ** 2)
    preload_n = 0.75 * proof_stress_mpa * stress_area_mm2
    torque_nm = 0.2 * d_m * preload_n

    return {
        "status": "success",
        "bolt_size": f"M{bolt_diameter_mm}",
        "grade": grade,
        "recommended_torque_nm": round(torque_nm, 2),
        "preload_force_n": round(preload_n, 1)
    }
